export const STICKER_SIZES = {
  mini: {
    label: "Mini",
    desc: "~10mm × 10mm",
    note: "(Recommended)",
    w: 160,
    h: 175,
    qrSize: 90,
    qrY: 34,
    idY: 125,
    boxY: 138,
    boxW: 120,
    boxH: 14,
    rewardTextY: 148,
    securedTextY: 146,
    footerY: 160,
    printW: 120,
    printH: 135,
    printTitleSize: 9,
    printSubSize: 6,
    printQrSize: 80,
    printIdSize: 7,
    printRewardSize: 8,
    printSecuredSize: 7,
    printFooterSize: 6,
    gridCols: "grid-cols-2 sm:grid-cols-3 md:grid-cols-4",
    printGridCols: "repeat(3, 1fr)",
  },
  standard: {
    label: "Standard",
    desc: "~25mm × 25mm",
    note: "",
    w: 280,
    h: 300,
    qrSize: 160,
    qrY: 60,
    idY: 212,
    boxY: 230,
    boxW: 220,
    boxH: 22,
    rewardTextY: 244,
    securedTextY: 242,
    footerY: 274,
    printW: 180,
    printH: 200,
    printTitleSize: 12,
    printSubSize: 8,
    printQrSize: 120,
    printIdSize: 10,
    printRewardSize: 10,
    printSecuredSize: 9,
    printFooterSize: 7,
    gridCols: "grid-cols-1 sm:grid-cols-2 md:grid-cols-3",
    printGridCols: "repeat(2, 1fr)",
  },
} as const;

export type StickerSizeKey = keyof typeof STICKER_SIZES;
